version: '3.9'

services: 

    mongo:
        image: mongo
        restart: always
        ports: 
            - 27117:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret
        volumes:
            - mongodb:/data/db

    back:
        depends_on: 
            - mongo
        build: 
            dockerfile: Dockerfile
            context: .
        ports: 
            - 5042:5000
        restart: always
        
volumes:
    mongodb:           
